### ISSUE TITLE
nemo-python: 404 error

### ISSUE THREAD

**Issue by thegreyshadow** [Skaendo/csb-extras#1]
Branch: master
Source package for nemo-python cannot be found:

# ./nemo-python.SlackBuild 
--2016-11-17 10:48:57--  http://packages.linuxmint.com/pool/main/n/nemo-python/nemo-python_3.0.0+betsy.tar.gz
Resolving packages.linuxmint.com (packages.linuxmint.com)... 68.235.39.11, 208.77.20.11
Connecting to packages.linuxmint.com (packages.linuxmint.com)|68.235.39.11|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-11-17 10:48:58 ERROR 404: Not Found.

**Comment by Skaendo** [comment]
Something upstream must have changed or they are down. I will look into it. Next time could you just open 1 issue for all of these errors that are the same, thanks.

**Comment by thegreyshadow** [comment]
Ok, sorry for the spam. I will take this into account.
Thanks!

**Comment by Skaendo** [comment]
No big deal about the spam. I have upgraded the scripts to versions 3.2.0+ but I have not yet tested them. I am setting that up right now. For some reason upstream has removed the 3.0.0 sources and packages. I do not know why, but everything before 3.0 is still there. I am assuming that the 3.2.0 packages are intended for Cinnamon 3.2, but they should work on Willy's "stable" scripts as well. If you want to test the 3.2.0 scripts here I would much appreciate it and any feedback. Thanks!

**Comment by Skaendo** [comment]
I updated all the scripts with links to new packages and they seem to be working fine now with the exception of nemo-seahorse which I removed until I can get it working (it hasn't worked since I added it). I am closing all the issues now.

**Comment by thegreyshadow** [comment]
Thank you Skaendo. 3.2 is fine since I built willy's 3.2-pre branch. I can say that all your packages now build correctly.
