### ISSUE TITLE
libnemo-extension-dev: 404 error

### ISSUE THREAD

**Issue by thegreyshadow** [Skaendo/csb-extras#2]
Branch: master
`` # ./libnemo-extension-dev.SlackBuild 
--2016-11-17 11:10:24--  http://packages.linuxmint.com/pool/main/n/nemo/libnemo-extension-dev_3.0.6+betsy_amd64.deb
Resolving packages.linuxmint.com (packages.linuxmint.com)... 68.235.39.11, 208.77.20.11
Connecting to packages.linuxmint.com (packages.linuxmint.com)|68.235.39.11|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-11-17 11:10:30 ERROR 404: Not Found.
``

**Comment by Skaendo** [comment]
Fixed/closed.

**Comment by thegreyshadow** [comment]
thank you!
