### ISSUE TITLE
nemo-dropbox: 404 error

### ISSUE THREAD

**Issue by thegreyshadow** [Skaendo/csb-extras#3]
Branch: master
``
# ./nemo-dropbox.SlackBuild 
--2016-11-17 11:14:34--  http://packages.linuxmint.com/pool/main/n/nemo-dropbox/nemo-dropbox_3.0.0+betsy.tar.gz
Resolving packages.linuxmint.com (packages.linuxmint.com)... 68.235.39.11, 208.77.20.11
Connecting to packages.linuxmint.com (packages.linuxmint.com)|68.235.39.11|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-11-17 11:14:35 ERROR 404: Not Found.
``

**Comment by Skaendo** [comment]
Fixed/closed.

**Comment by thegreyshadow** [comment]
Thank you!
