### ISSUE TITLE
nemo-emblems: 404 error

### ISSUE THREAD

**Issue by thegreyshadow** [Skaendo/csb-extras#4]
Branch: master
``
# ./nemo-emblems.SlackBuild 
--2016-11-17 11:15:43--  http://packages.linuxmint.com/pool/main/n/nemo-emblems/nemo-emblems_3.0.1.tar.gz
Resolving packages.linuxmint.com (packages.linuxmint.com)... 68.235.39.11, 208.77.20.11
Connecting to packages.linuxmint.com (packages.linuxmint.com)|68.235.39.11|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-11-17 11:15:44 ERROR 404: Not Found.
``

**Comment by Skaendo** [comment]
Fixed/closed.

**Comment by thegreyshadow** [comment]
Thank you!
